---
name: concourse

releases:
- name: concourse
  version: 3.0.1
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.0.1
  sha1: ade4f7b6a939d3a47590006410aa89f69b4dbd1f
- name: garden-runc
  version: 1.7.0
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.7.0
  sha1: 18366fade5189aa563b4787db3ef3b4376d4e76c

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:

- name: db
  instances: 1
  vm_type: default
  stemcell: trusty
  persistent_disk_type: 1GB
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: "((database_name))"
        role: "((database_username))"
        password: "((database_password))"

- name: web
  instances: 1
  vm_type: default
  vm_extensions:
  - lb
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: "https://((domain))"

      basic_auth_username: "((basic_auth_username))"
      basic_auth_password: "((basic_auth_password))"
      postgresql_database: "((database_name))"
  - name: tsa
    release: concourse
    properties: {}

- name: worker
  instances: 1
  vm_type: default
  vm_extensions:
  - 5GB_ephemeral_disk
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-90000

variables: 
- name: basic_auth_username
  type: password
- name: basic_auth_password
  type: password
- name: database_name
  type: password
- name: database_username
  type: password
- name: database_password
  type: password
- name: atc_ca
  type: certificate
  options:
    is_ca: true
    common_name: atcCA
- name: atc
  type: certificate
  options:
    ca: atc_ca
